export const reasonTypes = {
  PAYMENT: 'PAYMENT',
  PAYOUT: 'PAYOUT',
  PAYOUT_ROLLBACK: 'PAYOUT_ROLLBACK',
  DEPOSIT_PROFIT: 'DEPOSIT_PROFIT',
  REFERRAL_PROFIT: 'REFERRAL_PROFIT',
  DEPOSIT_PAYOUT: 'DEPOSIT_PAYOUT',
  DEPOSIT_PAYMENT: 'DEPOSIT_PAYMENT',
}
